web:
    build: .
    ports:
        - "8081:8081"
    expose:
        - "8081"
    volumes:
        - ./:/var/www/html
        - ./.nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir:
        /var/www/html